export const ADD_TO_CART = 'ADD_TO_CART'

export const INIT_LAYOUT = 'INIT_LAYOUT'
export const SET_LAYOUT_STATUS = 'SET_LAYOUT_STATUS'
export const SET_MENU_LIST = 'SET_MENU_LIST'
export const SET_TAB_LIST = 'SET_TAB_LIST'
export const ADD_TAB = 'ADD_TAB'
export const OPEN_TAB = 'OPEN_TAB'
export const REMOVE_TAB = 'REMOVE_TAB'
export const SET_CURRENT_PATH = 'SET_CURRENT_PATH'
export const SET_OPENED_MENU_LIST = 'SET_OPENED_MENU_LIST'
